spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/simple-admin?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  redis:
    host: 127.0.0.1
    database: 3
    port: 6379
    password: 123456

logging:
  level:
    org:
      wf:
        jwtp: info

jwtp:
  exclude-path: /**